---
# Three Tier Application Playbook
- name: Config ACI Basics
  hosts: apic1
  connection: local
  gather_facts: no

  vars_files:
    - /root/ansible_aci/basic_vars.yaml

  tasks:
  - name: Creating Contracts
    aci_contract:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      contract: "{{ item.contract }}"
      tenant: "{{ tenant }}"
      scope: "context"
      validate_certs: no
      state: present
    loop:
      - contract: "{{ web_to_app_contract }}"
      - contract: "{{ app_to_db_contract }}"

  - name: Add Filters
    aci_filter:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      #filter: "{{ http_filter }}"
      filter: "{{ item.filter }}"
      tenant: "{{ tenant }}"
      validate_certs: no
      state: present
    loop:
      - filter: "{{ http_filter }}"
      - filter: "{{ db_filter }}"

  - name: Add Port 80 and 1433 to Filter entries
    aci_filter_entry:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      entry: "{{ item.entry }}"
      tenant: "{{ tenant }}"
      ether_type: ip
      ip_protocol: tcp
      dst_port: "{{ item.dst_port }}"
      filter: "{{ item.filter }}"
      validate_certs: no
      state: present
    loop:
      - entry: "{{ http_filter_entry }}"
        dst_port: 80
        filter: "{{ http_filter }}"
      - entry: "{{ db_filter_entry }}"
        dst_port: 1433
        filter: "{{ db_filter }}"

  - name: Bind subjects to contracts
    aci_contract_subject:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{ tenant }}"
      contract: "{{ item.contract }}"
      subject: "{{ item.subject }}"
      reverse_filter: yes
      validate_certs: no
      state: present
    loop:
      - contract: "{{ web_to_app_contract }}"
        subject: "{{ web_to_app_contract_subject }}"
      - contract: "{{ app_to_db_contract }}"
        subject: "{{ app_to_db_contract_subject }}"

  - name: Bind Contract Subjects to filter
    aci_contract_subject_to_filter:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{ tenant }}"
      contract: "{{ item.contract }}"
      filter: "{{ item.filter }}"
      subject: "{{ item.subject }}"
      validate_certs: no
      state: present
    loop:
      - contract: "{{ web_to_app_contract }}"
        filter: "{{ http_filter }}"
        subject: "{{ web_to_app_contract_subject }}"
      - contract: "{{ app_to_db_contract }}"
        filter: "{{ db_filter }}"
        subject: "{{ app_to_db_contract_subject }}"

  - name: Create Physical Domain
    aci_domain:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      domain: baremetal
      domain_type: phys
      state: present

  - name: Create VLAN Pool
    aci_vlan_pool:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      pool: baremetal
      pool_allocation_mode: static
      state: present

  - name: Create VLAN Range
    aci_encap_pool_range:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      pool: baremetal
      pool_allocation_mode: static
      pool_type: vlan
      range_name: baremetal
      range_start: 100
      range_end: 1000
      allocation_mode: inherit
      state: present

  - name: Bind Domain to Pool
    aci_domain_to_vlan_pool:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      pool: baremetal
      pool_allocation_mode: static
      domain: baremetal 
      domain_type: phys 
      state: present
 
  - name: Create AEP
    aci_aep:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      aep: baremetal
      state: present

  - name: Map AEP
    aci_aep_to_domain:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      aep: baremetal
      domain: baremetal 
      domain_type: phys 
      state: present

  - name: Leaf Interface Profile
    aci_interface_policy_leaf_policy_group:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      policy_group: baremetal
      lag_type: leaf
      aep: baremetal
      state: present

  - name: Create L3 Domain
    aci_domain:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      domain: l3out
      domain_type: l3dom
      state: present

  - name: Create AEP
    aci_aep:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      aep: l3out
      state: present

  - name: Map AEP
    aci_aep_to_domain:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      aep: l3out
      domain: l3out
      domain_type: l3dom
      state: present


